### ISSUE TITLE
About rendering_with_merl.py

### ISSUE THREAD

**Issue by WANGYINGYU** [hiroaki-santo/deep-photometric-stereo-network#2]
Hello,
When I run "python rendering_with_merl.py",the error occured as follow.

> Traceback (most recent call last):
  File "rendering_with_merl.py", line 163, in <module>
    for n_path in n_png_paths[[1, 7]]:  # This means blob02 and blob08
IndexError: index 1 is out of bounds for axis 1 with size 0

Can you solve it?Thank you.

**Comment by hiroaki-santo** [comment]
Are you sure that Blobby dataset is extracted at the correct directory path?
`n_png_paths` is from `glob.glob(params.BLOBS_PATH)`.
(`params.BLOBS_PATH = "./blobs/blobs/data/blob*_n.png"`)

**Comment by JonathanHe2018** [comment]
Hi,
When I run "python rendering_with_merl.py",the error occured as follow.
Traceback (most recent call last):
  File "rendering_with_merl.py", line 18, in <module>
    from merl_brdf_database import merl_brdf
  File "/home/jo/deep-photometric-stereo-network/merl_brdf_database/merl_brdf.py", line 9, in <module>
    import BRDFRead
ImportError: /home/jo/deep-photometric-stereo-network/merl_brdf_database/BRDFRead.so: undefined symbol: _ZN5boost5numpy5zerosERKNS_6python5tupleERKNS0_5dtypeE

**Comment by hiroaki-santo** [comment]
Did you run ``make`` in ``./merl_brdf_database``?
My code uses ``BRDFRead.cpp`` via ``Boost Numpy`` to read BRDF data, and so you need to compile.

**Comment by hasayake007** [comment]
hi，i do not understand the training data‘s size；
if the number of light source is 96 and the number of training data is 3.9e7，
so does the size of training data is [96*3,3.9e7]?
and the size of output data is [3,3.9e7]?
could you please help me to understand this paper better？
Thank you.

**Comment by hasayake007** [comment]
> Hello,
> When I run "python rendering_with_merl.py",the error occured as follow.
> 
> > Traceback (most recent call last):
> > File "rendering_with_merl.py", line 163, in 
> > for n_path in n_png_paths[[1, 7]]:  # This means blob02 and blob08
> > IndexError: index 1 is out of bounds for axis 1 with size 0
> 
> Can you solve it?Thank you.

同学也是在研究光度立体吗？可以交流一下吗

**Comment by hiroaki-santo** [comment]
Hi hasayake007, Thank you for your question about the number of training data.
The number 3.9e7 is the number of the set of the measurement vector and normal vector.

In terms of images, we render 8 x 100 x 96 images (8: #normal maps, 100: #materials, 96: #light sources).
Then we generate a training set in a per-pixel manner, and so one pixel has the measurement vector (96-dim ) and normal vector ( 3-dim).
The number of pixels is 256 x 192 and so the number of the training set is 8 x 100 x 256 x 192.

**Comment by hasayake007** [comment]
Thank you for your reply！！
But maybe I do not explain my question clearly which makes you misunderstand....
My question is not about the number of training data  rather than  the Dimension of  training data.
I think the dimension of training data is [96x3,3.9e7]（96: #light sources，3：#RGB,  3.9e7=8 x 100 x 256 x 192.）
and output data is [3,3.9e7],(3:#nx,ny,nz);
Do I think about right？

**Comment by hiroaki-santo** [comment]
I see. Sorry for my misunderstanding.
In teams of the dimensions of training data, you're right.

**Comment by hasayake007** [comment]
thanks very much！ best wishes  for you！！

**Comment by Maggieli** [comment]
> Hi,
> When I run "python rendering_with_merl.py",the error occured as follow.
> Traceback (most recent call last):
> File "rendering_with_merl.py", line 18, in 
> from merl_brdf_database import merl_brdf
> File "/home/jo/deep-photometric-stereo-network/merl_brdf_database/merl_brdf.py", line 9, in 
> import BRDFRead
> ImportError: /home/jo/deep-photometric-stereo-network/merl_brdf_database/BRDFRead.so: undefined symbol: _ZN5boost5numpy5zerosERKNS_6python5tupleERKNS0_5dtypeE

Hi! I have met the same problem. Have you ever solved it?

**Comment by hiroaki-santo** [comment]
I guess your error is related to Boost::Python. I'm not sure but Linker can not find the libraries?
I think you need to correct the Cmakefile to suit your environment.

**Comment by Maggieli** [comment]
Thanks a lot！



    


            On 01/27/2019 01:23, Hiroaki Santo wrote: I guess your error is related to Boost::Python. I'm not sure but Linker can not find the libraries?
I think you need to correct the Cmakefile to suit your environment.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/hiroaki-santo/deep-photometric-stereo-network","title":"hiroaki-santo/deep-photometric-stereo-network","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/hiroaki-santo/deep-photometric-stereo-network"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hiroaki-santo in #2: I guess your error is related to Boost::Python. I'm not sure but Linker can not find the libraries?\r\nI think you need to correct the Cmakefile to suit your environment. "}],"action":{"name":"View Issue","url":"https://github.com/hiroaki-santo/deep-photometric-stereo-network/issues/2#issuecomment-457848774"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/hiroaki-santo/deep-photometric-stereo-network/issues/2#issuecomment-457848774",
"url": "https://github.com/hiroaki-santo/deep-photometric-stereo-network/issues/2#issuecomment-457848774",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
